# Site settings
title: Elliott Minns
email: elliott.minns@me.com
description: "Freelance iOS, Android and Cloud Developer based in London. Specialising in Swift, Objective-C, Node.js, Javascript, Web, HTML & CSS. Based in London UK."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/elliottwins
  - title: linkedin
    url: http://uk.linkedin.com/pub/elliott-minns/2b/18b/785/
  - title: github
    url: http://github.com/elliott-minns

# Postal address (add as many lines as necessary)
address:
  - line: 27a Cato Road
  - line: London, SW4

# Build settings
markdown: kramdown
permalink: pretty
